apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: argo-test-wf-
spec:
    entrypoint: NoName
    podGC:
        strategy: OnPodSuccess
    ttlStrategy:
        secondsAfterCompletion: 60
    templates:
        - name: task
          container:
            image: liudy093/task:latest
            imagePullPolicy: IfNotPresent
            resources:
                limits:
                    cpu: 2000m
                    memory: 128Mi
                requests:
                    cpu: 1000m
                    memory: 64Mi
        - name: NoName
          dag:
            tasks:
                - name: t0
                  dependencies: []
                  template: task
                - name: t1
                  dependencies:
                    - t0
                  template: task
                - name: t2
                  dependencies:
                    - t0
                  template: task
                - name: t5
                  dependencies:
                    - t1
                    - t2
                  template: task
                - name: t3
                  dependencies:
                    - t0
                  template: task
                - name: t4
                  dependencies:
                    - t0
                  template: task
                - name: t6
                  dependencies:
                    - t3
                    - t4
                  template: task
                - name: t7
                  dependencies:
                    - t5
                    - t6
                  template: task
